In [1]:
# Import Dependencies
import pandas as pd

In [3]:
# Read in our unclean data
df = pd.read_csv('state_data.csv')
df.columns

Index(['State', 'Sector', 'Year', 'Employment (2012=100)',
       'Employment (percent change)', 'Hourly labor compensation (2012=100)',
       'Hourly labor compensation (percent change)',
       'Hourly labor compensation cost ($/hour)',
       'Hourly labor compensation cost (percent change)', 'Hours (2012=100)',
       'Hours (percent change)', 'Implicit output deflator (2012=100)',
       'Implicit output deflator (percent change)',
       'Labor compensation (2012=100)', 'Labor compensation (percent change)',
       'Labor compensation cost (million $)',
       'Labor compensation cost (percent change)',
       'Labor productivity (2012=100)', 'Labor productivity (percent change)',
       'Number of employees (percent change)',
       'Number of employees (thousands)', 'Number of hours (millions)',
       'Number of hours (percent change)', 'Output (2012=100)',
       'Output (percent change)', 'Output per employee (2012=100)',
       'Output per employee (percent change)',
       'Real hourly labor compensation (2012=100)',
       'Real hourly labor compensation (percent change)',
       'Real hourly labor compensation cost ($/hour)',
       'Real hourly labor compensation cost (percent change)',
       'Real labor compensation (2012=100)',
       'Real labor compensation (percent change)',
       'Real labor compensation cost (million $)',
       'Real labor compensation cost (percent change)',
       'Unit labor cost (2012=100)', 'Unit labor cost (percent change)',
       'Value of production (million $)',
       'Value of production (percent change)'],
      dtype='object')

In [5]:
# Grab the only columns we want
labor_df = df[[
    'State',
    'Year',
    'Labor productivity (2012=100)',
    'Labor productivity (percent change)',
    'Real hourly labor compensation cost ($/hour)',
    'Real hourly labor compensation cost (percent change)',
    'Value of production (million $)'
]]

# Make a list of the only years that we want
year_list = [2015, 2016, 2017, 2018, 2019]

# And then grab only the years that we want from the data
clean_data = labor_df[labor_df['Year'].isin(year_list)]
clean_data.head(10)

,State,Year,Labor productivity (2012=100),Labor productivity (percent change),Real hourly labor compensation cost ($/hour),Real hourly labor compensation cost (percent change),Value of production (million $)
8,Alabama,2015,99.748,-0.3,34.508,2.8,153074.368
9,Alabama,2016,98.518,-1.2,34.599,0.3,156265.773
10,Alabama,2017,99.447,0.9,34.840,0.7,161411.784
11,Alabama,2018,101.454,2.0,35.046,0.6,171145.010
12,Alabama,2019,103.805,2.3,35.662,1.8,179040.839
21,Alaska,2015,94.657,1.8,39.006,3.4,37739.819
22,Alaska,2016,94.911,0.3,37.707,-3.3,36367.452
23,Alaska,2017,96.170,1.3,36.692,-2.7,38759.476
24,Alaska,2018,95.915,-0.3,37.476,2.1,41275.436
25,Alaska,2019,96.424,0.5,38.023,1.5,41595.986

In [7]:
# Then we'll write our clean data to a csv
clean_data.to_csv('clean_data.csv', index= False)